In [1]:
import numpy as np

# Ocena klasyfikacji binarnej
def classification_metrics(correct, predicted):
    tp = np.sum((correct == 1) & (predicted == 1)) # TruePositive
    tn = np.sum((correct == 0) & (predicted == 0)) # TrueNegative
    fp = np.sum((correct == 0) & (predicted == 1)) # FalsePositive (błąd typu I)
    fn = np.sum((correct == 1) & (predicted == 0)) # FalseNegative (błąd typu II)

    accuracy = (tp + tn) / (tp + tn + fp + fn)
    precision = tp / (tp + fp) if (tp + fp) != 0 else 0
    recall = tp / (tp + fn) if (tp + fn) != 0 else 0
    f1 = 2 * (precision * recall) / (precision + recall) if (precision + recall) != 0 else 0

    return accuracy, precision, recall, f1

# Przykladowe dane
correct = np.array([0,1,0,1,1,1,0,0,1,1,0])
predicted = np.array([1,1,0,0,1,1,1,0,0,0,0])

accuracy, precision, recall, f1 = classification_metrics(correct, predicted)
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")

Accuracy: 0.5454545454545454
Precision: 0.6
Recall: 0.5
F1 Score: 0.5454545454545454


In [ ]:
class Perceptron:
    def __init__(self, num_features, epochs = 500, learning_rate=0.01, epsilon=1e-10):
        self.weights = np.random.rand(num_features)
        self.bias = np.random.rand(1)[0]
        self.epochs = epochs
        self.epsilon = epsilon
        self.learning_rate = learning_rate

    def predict(self, x): # funkcja aktywacji
        return np.where(np.dot(x, self.weights) + self.bias >= 0, 1, 0)
    
    def train(self, x_train, y_train):
            for _ in range(self.epochs):
                prev_weights = self.weights.copy()

                for x, y in zip(x_train, y_train):
                    prediction = self.predict(x)
                    update = y - prediction  # -1, 0, lub 1; jeśli 0 to wagi się nie aktualizują, ponieważ była poprawna predykcja
                    
                    self.weights += self.learning_rate * update * x
                    self.bias += self.learning_rate * update

                # Sprawdzenie, czy wagi się stabilizują
                if np.linalg.norm(self.weights - prev_weights) < self.epsilon:
                    break
 
    def test(self, X):
        return np.where( X @ self.weights + self.bias >= 0, 1, 0)

In [17]:
import csv    
def open_csv(file_path):
    x, y = [], []
    with open(file_path, 'r') as csvfile:
        csvreader = csv.reader(csvfile, delimiter=' ')
        for row in csvreader:
            x.append(list(map(float, row[:-1])))
            y.append(int(row[-1]))
    return np.array(x), np.array(y)

x, y = open_csv('dataset.csv')       
print(x)
print(y)
x_train = x[:7000]
y_train = y[:7000]

x_test = x[7000:]
y_test = y[7000:]

[[15.73094725  7.18528284 64.41038317 24.66428237]
 [83.44155279 63.01982687 75.83614336 67.61127283]
 [99.39100517  9.61315971 14.93347999 72.15498409]
 ...
 [87.97905359 25.80428991 22.24284486 88.04449276]
 [80.20238287 21.64052602 41.48732363  3.6147353 ]
 [ 0.62492591 99.65803104 81.97150773 77.52295713]]
[0 1 1 ... 1 0 0]


In [20]:
perceptron = Perceptron(4)
perceptron.train(x_train, y_train)

predicted = perceptron.test(x_test)
print(predicted)

[ True  True  True ...  True False  True]


In [24]:
accuracy, precision, recall, f1 = classification_metrics(y_test, np.where(predicted,1, 0))
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")

Accuracy: 0.8146666666666667
Precision: 0.6992969172525689
Recall: 1.0
F1 Score: 0.8230426479949077
